[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.17"
optimizer_runs = 100_000
gas_reports = ["Pair", "Caviar", "LpToken"]

[profile.default.fuzz]
runs = 256

[fmt]
line_length = 120

# See more config options https://github.com/foundry-rs/foundry/tree/master/config